### ISSUE TITLE
Broken links (meta ticket)

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#699]
Just for keeping track...

- [ ] Footer: geting started
- [ ] Footer: bug reporting guide
- [ ] http://scala-lang.org/documentation/getting-started/
- [ ] http://scala-lang.org/documentation/api/
- [x] http://scala-lang.org/contribute/bug-reporting-guide/
- [x] http://scala-lang.org/resources/img/twitter-logo.png
- [ ] https://gitter.im/scala/scala-parser-combinator
- [ ]  http://scala-lang.org/community/index.html

https://validator.w3.org/checklink?uri=scala-lang.org&hide_type=all&depth=&check=Check

**Comment by martijnhoekstra** [comment]
http://docs.scala-lang.org/tutorials/FAQ/ contains broken links too

**Comment by martijnhoekstra** [comment]
A crawl additionally gives me

* https://www.scala-lang.org/contribute/
* https://www.scala-lang.org/documentation/getting-started-intellij-track/testing-scala-in-intellij-with-scalatest.html
* https://www.scala-lang.org/documentation/getting-started-sbt-track/getting-started-with-scala-and-sbt-in-the-command-line.html
* https://www.scala-lang.org/download/changelog.html
* https://www.scala-lang.org/blog/2017/03/13/spark-mooc-capstone-live-on-coursera.html
* https://www.scala-lang.org/news/2017/02/22/gsoc-2017.html
* https://www.scala-lang.org/news/2014/02/24/scala-team-approved-to-be-gsoc-mentor-organization.html
* https://www.scala-lang.org/news/2015/03/16/GSoC-projects.html

and, (unrelatedly)

* http(s)://www.scala-lang.org/files/archive/spec/2.12/05-classes-and-objects.html
* http(s)://www.scala-lang.org/files/archive/spec/2.11/05-classes-and-objects.html

where I excluded

* http(s)?://(www.)?scala-lang.org/(files/)?(archive/)?api/.*
* http(s)?://(www.)?scala-lang.org/(files/)?old/.*
* http(s)?://(www.)?scala-lang.org/(files/)?archive/.*
* /documentation/getting-started/

**Comment by janekdb** [comment]
On http://www.scala-lang.org/contribute/ clicking "COMPILER/LANGUAGE" gives `Not Found`

http://www.scala-lang.org/contribute/guide/#larger-changes-new-features

**Comment by SethTisue** [comment]
@Philippus should we close this now?

**Comment by Philippus** [comment]
yes, I think all/most of these have been addressed already.... the validator.w3.org link looks pretty clean to me.

**Comment by SethTisue** [comment]
sweeeeeeet
